### ISSUE TITLE
Use different tag for images released for the same version of Golang

### ISSUE THREAD

**Issue by jsoriano** [elastic/golang-crossbuild#104]
golang-crossbuild images are tagged only with the included version of Go and the architecture. If build scripts are modified, a new image can be built with the same tag as a previously built image. If the new image includes some backwards incompatibility by mistake, it can end up affecting consumers of these images, that don't have a way of controlling the exact image used.

A different tagging policy, that takes into consideration changes in the build scripts, could allow to make changes in the images without affecting consumers. Consumers could update the images used in a controlled way.

This affected Beats after some refactors in ARM images https://github.com/elastic/beats/pull/25987.

**Comment by kuisathaverat** [comment]
if we want to consume always the same Docker image until we force the update we should use the SHA256 and no a tag, this SHA256 does not change and point always to the same Docker image. For example instead of using `docker.elastic.co/beats-dev/golang-crossbuild:1.15.12-darwin-debian10` we would use `docker.elastic.co/beats-dev/golang-crossbuild@sha256:ac7f5412707c7286d7c21a8fd3fcf26e2379b2cbd1532386a1742c317ff340b3` in this case if we generate a new Docker image for 1.15.12-darwin-debian10 this will not be used until we update the SHA on the beats repo. We can put something that automates the process and makes a new PR to the beats repo to update/test the new Docker images.

About the tagging of the crossbuild Docker images I would say that we have to rid of some tags and make them more clear, for example, `arm` that contains `ARM64` crosscompiler should be changed to `arm64` and `arm` disappear.

* arm -> arm64
* mips -> mips64
* ppc -> ppc64

**Comment by jsoriano** [comment]
SGTM, we will need some tool to help updating the tags.

**Comment by kuisathaverat** [comment]
there is a task created for implementing the feature, I think we can close the issue.
